// Your array
const array = [
  "Dresses",
  "Dress",
  "Clothing",
  "Clothes",
  "Cloth",
  "Cowl",
  "Cowls Necks",
  "Cowl Necks",
  "Cowls Neck",
  "Cowl Detail",
  "Cowl Detailed",
  "Cowl Details",
  "Cowl Dresses",
  "Cowl Neckline Dresses",
  "Cowl Neckline Dress",
  "Cowl Neckline Clothing",
  "Cowl Neckline Clothes",
  "Cowl Neckline Cloth",
  "Cowls Dresses",
  "Cowls Dress",
  "Cowls Clothing",
  "Cowls Clothes",
  "Cowls Cloth",
  "Cowl Necks Dresses",
  "Cowl Necks Dress",
  "Cowl Necks Clothing",
  "Cowl Necks Clothes",
  "Cowl Necks Cloth",
  "Cowl Details Dresses",
  "Cowl Details Dress",
  "Cowl Details Clothing",
  "Cowl Details Clothes",
  "Cowl Details Cloth",
  "Cowl Detailed Dresses",
  "Cowl Detailed Dress",
  "Cowl Detailed Clothing",
  "Cowl Detailed Clothes",
  "Cowl Detailed Cloth",
  "Cowl Detail Dresses",
  "Cowl Detail Dress",
  "Cowl Detail Clothing",
  "Cowl Detail Clothes",
  "Cowl Detail Cloth",
  "Women",
  "Women Dresses",
  "Mini",
  "Maxi",
  "Minis",
  "Micro Mini",
  "Short",
  "Short Dress",
  "Short Dresses",
  "Maxis Length",
  "Maxis Style",
  "Maxi Length",
  "Full Length",
  "Full Lengths",
  "Mini Dresses",
  "Maxi Dresses",
  "Micro Mini Dresses",
  "Micro Mini Dress",
  "Micro Mini Clothing",
  "Micro Mini Clothes",
  "Micro Mini Cloth",
  "Micro Minis Dresses",
  "Micro Minis Dress",
  "Micro Minis Clothing",
  "Micro Minis Clothes",
  "Micro Minis Cloth",
  "Mini Dress",
  "Mini Clothing",
  "Mini Clothes",
  "Mini Cloth",
  "Short Dresses Dresses",
  "Short Dresses Dress",
  "Short Dresses Clothing",
  "Short Dresses Clothes",
  "Short Dresses Cloth",
  "Short Clothing",
  "Short Clothes",
  "Short Cloth",
  "es",
  "",
  "x",
  "Short Dress Clothes",
  "Short Dress Cloth",
  "Maxis Dresses",
  "Maxis Dress",
  "Maxis Clothing",
  "Maxis Clothes",
  "Maxis Cloth",
  "Maxi Dress",
  "Maxi Clothing",
  "Maxi Clothes",
  "Maxi Cloth",
  "Maxi Length Dresses",
  "Maxi Length Dress",
  "Maxi Length Clothing",
  "Maxi Length Clothes",
  "Maxi Length Cloth",
  "Full Length Dresses",
  "Full Length Dress",
  "Full Length Clothing",
  "Full Length Clothes",
  "Full Length Cloth",
  "Full Lengths Dresses",
  "Full Lengths Dress",
  "Full Lengths Clothing",
  "Full Lengths Clothes",
  "Full Lengths Cloth",
  "Sleeveless",
  "Sleeve Less",
  "No Sleeve",
  "No Sleeves",
  "Sleeveless Dresses",
  "Sleeve Less Dresses",
  "Sleeve Less Dress",
  "Sleeve Less Clothing",
  "Sleeve Less Clothes",
  "Sleeve Less Cloth",
  "No Sleeve Dresses",
  "No Sleeve Dress",
  "No Sleeve Clothing",
  "No Sleeve Clothes",
  "No Sleeve Cloth",
  "No Sleeves Dresses",
  "No Sleeves Dress",
  "No Sleeves Clothing",
  "No Sleeves Clothes",
  "No Sleeves Cloth",
  "Slip",
  "Shift",
  "Slip Dress",
  "Slip Dresses",
  "Slip On",
  "Slip On Dresses",
  "Slip On Dress",
  "Shifts Styles",
  "Shifts",
  "Shifts Styled",
  "Aqua",
  "Blue",
  "Aqua Dresses",
  "Blue Dresses",
  "Shift Dresses",
  "Slip Dresses Dresses",
  "Slip Dresses Dress",
  "Slip Dresses Clothing",
  "Slip Dresses Clothes",
  "Slip Dresses Cloth",
  "Slip Dress Dresses",
  "Slip Dress Dress",
  "Slip Dress Clothing",
  "Slip Dress Clothes",
  "Slip Dress Cloth",
  "Slip On Dresses Dresses",
  "Slip On Dresses Dress",
  "Slip On Dresses Clothing",
  "Slip On Dresses Clothes",
  "Slip On Dresses Cloth",
  "Slip On Dress Dresses",
  "Slip On Dress Dress",
  "Slip On Dress Clothing",
  "Slip On Dress Clothes",
  "Slip On Dress Cloth",
  "Slip On Clothing",
  "Slip On Clothes",
  "Slip On Cloth",
  "Shifts Styled Dresses",
  "Shifts Styled Dress",
  "Shifts Styled Clothing",
  "Shifts Styled Clothes",
  "Shifts Styled Cloth",
  "Shift Styles Dresses",
  "Shift Styles Dress",
  "Shift Styles Clothing",
  "Shift Styles Clothes",
  "Shift Styles Cloth",
  "Shift Dress",
  "Shift Clothing",
  "Shift Clothes",
  "Shift Cloth",
  "Abstract",
  "Abstract Prints",
  "Abstract Print",
  "Abstract Printed",
  "Abstract Dresses",
  "Abstract Prints Dresses",
  "Abstract Prints Dress",
  "Abstract Prints Clothing",
  "Abstract Prints Clothes",
  "Abstract Prints Cloth",
  "Abstract Print Dresses",
  "Abstract Print Dress",
  "Abstract Print Clothing",
  "Abstract Print Clothes",
  "Abstract Print Cloth",
  "Abstract Dress",
  "Abstract Clothing",
  "Abstract Clothes",
  "Abstract Cloth",
  "Main Collection",
  "Main Collections",
  "Main Collection Dresses",
  "Main Collections Dresses",
  "Main Collections Dress",
  "Main Collections Clothing",
  "Main Collections Clothes",
  "Main Collections Cloth",
  "Main Collection Dress",
  "Main Collection Clothing",
  "Main Collection Clothes",
  "Main Collection Cloth",
  "Shop By Occasion",
  "Summer Brights",
  "Shop By Trend",
  "Black Friday",
  "Date Night",
  "Party",
  "Festival",
  "Holiday",
  "Summer",
  "Going Out",
  "Spring",
  "Occasion",
  "Formal",
  "Shop By Occasion Dresses",
  "Summer Brights Dresses",
  "Shop By Trend Dresses",
  "Black Friday Dresses",
  "Date Night Dresses",
  "Party Dresses",
  "Festival Dresses",
  "Holiday Dresses",
  "Summer Dresses",
  "Going Out Dresses",
  "Spring Dresses",
  "Occasion Dresses",
  "Formal Dresses",
  "Crystal",
  "Embellished",
  "Crystal Dresses",
  "Embellished Dresses",
  "Abstract Mini Dresses",
  "Abstract Maxi Dresses",
  "Abstract Minis Dresses",
  "Abstract Minis Dress",
  "Abstract Minis Clothing",
  "Abstract Minis Clothes",
  "Abstract Minis Cloth",
  "Abstract Mini Dress",
  "Abstract Mini Clothing",
  "Abstract Mini Clothes",
  "Abstract Mini Cloth",
  "Abstract Micro Minis Dresses",
  "Abstract Micro Minis Dress",
  "Abstract Micro Minis Clothing",
  "Abstract Micro Minis Clothes",
  "Abstract Micro Minis Cloth",
  "Abstract Short Dresses Dresses",
  "Abstract Short Dresses Dress",
  "Abstract Short Dresses Clothing",
  "Abstract Short Dresses Clothes",
  "Abstract Short Dresses Cloth",
  "Abstract Short Dresses",
  "Abstract Short Dress",
  "Abstract Short Clothing",
  "Abstract Short Clothes",
  "Abstract Short Cloth",
  "Abstract es",
  "Abstract ",
  "Abstract",
  "Abstract Short Dress Clothes",
  "Abstract Short Dress Cloth",
  "Abstract Printed Minis Dresses",
  "Abstract Printed Minis Dress",
  "Abstract Printed Minis Clothing",
  "Abstract Printed Minis Clothes",
  "Abstract Printed Minis Cloth",
  "Abstract Printed Mini Dresses",
  "Abstract Printed Mini Dress",
  "Abstract Printed Mini Clothing",
  "Abstract Printed Mini Clothes",
  "Abstract Printed Mini Cloth",
  "Abstract Printed Micro Minis Dresses",
  "Abstract Printed Micro Minis Dress",
  "Abstract Printed Micro Minis Clothing",
  "Abstract Printed Micro Minis Clothes",
  "Abstract Printed Micro Minis Cloth",
  "Abstract Printed Short Dresses Dresses",
  "Abstract Printed Short Dresses Dress",
  "Abstract Printed Short Dresses Clothing",
  "Abstract Printed Short Dresses Clothes",
  "Abstract Printed Short Dresses Cloth",
  "Abstract Printed Short Dresses",
  "Abstract Printed Short Dress",
  "Abstract Printed Short Clothing",
  "Abstract Printed Short Clothes",
  "Abstract Printed Short Cloth",
  "Abstract Printed es",
  "Abstract Printed ",
  "Abstract Printed",
  "Abstract Printed Short Dress Clothes",
  "Abstract Printed Short Dress Cloth",
  "Abstract Prints Minis Dresses",
  "Abstract Prints Minis Dress",
  "Abstract Prints Minis Clothing",
  "Abstract Prints Minis Clothes",
  "Abstract Prints Minis Cloth",
  "Abstract Prints Mini Dresses",
  "Abstract Prints Mini Dress",
  "Abstract Prints Mini Clothing",
  "Abstract Prints Mini Clothes",
  "Abstract Prints Mini Cloth",
  "Abstract Prints Micro Minis Dresses",
  "Abstract Prints Micro Minis Dress",
  "Abstract Prints Micro Minis Clothing",
  "Abstract Prints Micro Minis Clothes",
  "Abstract Prints Micro Minis Cloth",
  "Abstract Prints Short Dresses Dresses",
  "Abstract Prints Short Dresses Dress",
  "Abstract Prints Short Dresses Clothing",
  "Abstract Prints Short Dresses Clothes",
  "Abstract Prints Short Dresses Cloth",
  "Abstract Prints Short Dresses",
  "Abstract Prints Short Dress",
  "Abstract Prints Short Clothing",
  "Abstract Prints Short Clothes",
  "Abstract Prints Short Cloth",
  "Abstract Prints es",
  "Abstract Prints ",
  "Abstract Prints",
  "Abstract Prints Short Dress Clothes",
  "Abstract Prints Short Dress Cloth",
  "Abstract Prints Maxis Dresses",
  "Abstract Prints Maxis Dress",
  "Abstract Prints Maxis Clothing",
  "Abstract Prints Maxis Clothes",
  "Abstract Prints Maxis Cloth",
  "Abstract Prints Maxi Dresses",
  "Abstract Prints Maxi Dress",
  "Abstract Prints Maxi Clothing",
  "Abstract Prints Maxi Clothes",
  "Abstract Prints Maxi Cloth",
  "Abstract Prints Maxi Style Dresses",
  "Abstract Prints Maxi Style Dress",
  "Abstract Prints Maxi Style Clothing",
  "Abstract Prints Maxi Style Clothes",
  "Abstract Prints Maxi Style Cloth",
  "Abstract Prints Full Length Dresses",
  "Abstract Prints Full Length Dress",
  "Abstract Prints Full Length Clothing",
  "Abstract Prints Full Length Clothes",
  "Abstract Prints Full Length Cloth",
  "Abstract Prints Full Lengths Dresses",
  "Abstract Prints Full Lengths Dress",
  "Abstract Prints Full Lengths Clothing",
  "Abstract Prints Full Lengths Clothes",
  "Abstract Prints Full Lengths Cloth",
  "Abstract Printed Maxis Dresses",
  "Abstract Printed Maxis Dress",
  "Abstract Printed Maxis Clothing",
  "Abstract Printed Maxis Clothes",
  "Abstract Printed Maxis Cloth",
  "Abstract Printed Maxi Dresses",
  "Abstract Printed Maxi Dress",
  "Abstract Printed Maxi Clothing",
  "Abstract Printed Maxi Clothes",
  "Abstract Printed Maxi Cloth",
  "Abstract Printed Maxi Style Dresses",
  "Abstract Printed Maxi Style Dress",
  "Abstract Printed Maxi Style Clothing",
  "Abstract Printed Maxi Style Clothes",
  "Abstract Printed Maxi Style Cloth",
  "Abstract Printed Full Length Dresses",
  "Abstract Printed Full Length Dress",
  "Abstract Printed Full Length Clothing",
  "Abstract Printed Full Length Clothes",
  "Abstract Printed Full Length Cloth",
  "Abstract Printed Full Lengths Dresses",
  "Abstract Printed Full Lengths Dress",
  "Abstract Printed Full Lengths Clothing",
  "Abstract Printed Full Lengths Clothes",
  "Abstract Printed Full Lengths Cloth",
  "Abstract Maxis Dresses",
  "Abstract Maxis Dress",
  "Abstract Maxis Clothing",
  "Abstract Maxis Clothes",
  "Abstract Maxis Cloth",
  "Abstract Maxi Dress",
  "Abstract Maxi Clothing",
  "Abstract Maxi Clothes",
  "Abstract Maxi Cloth",
  "Abstract Maxi Style Dresses",
  "Abstract Maxi Style Dress",
  "Abstract Maxi Style Clothing",
  "Abstract Maxi Style Clothes",
  "Abstract Maxi Style Cloth",
  "Abstract Full Length Dresses",
  "Abstract Full Length Dress",
  "Abstract Full Length Clothing",
  "Abstract Full Length Clothes",
  "Abstract Full Length Cloth",
  "Abstract Full Lengths Dresses",
  "Abstract Full Lengths Dress",
  "Abstract Full Lengths Clothing",
  "Abstract Full Lengths Clothes",
  "Abstract Full Lengths Cloth",
  "Strappy",
  "Hand Washed",
  "Country Of Origin China",
  "Satin Finish",
  "Strapy",
  "Straps",
  "Strap",
  "Strappy Dresses",
  "Hand Washed Dresses",
  "Country Of Origin China Dresses",
  "Satin Finish Dresses",
  "Straps Dresses",
  "Straps Dress",
  "Straps Clothing",
  "Straps Clothes",
  "Straps Cloth",
  "Strapy Dresses",
  "Strapy Dress",
  "Strapy Clothing",
  "Strapy Clothes",
  "Strapy Cloth",
  "Strap Dresses",
  "Strap Dress",
  "Strap Clothing",
  "Strap Clothes",
  "Strap Cloth",
  "Cowl Mini Dresses",
  "Cowl Maxi Dresses",
  "Cowls Neck Minis Dresses",
  "Cowls Neck Minis Dress",
  "Cowls Neck Minis Clothing",
  "Cowls Neck Minis Clothes",
  "Cowls Neck Minis Cloth",
  "Cowls Neck Mini Dresses",
  "Cowls Neck Mini Dress",
  "Cowls Neck Mini Clothing",
  "Cowls Neck Mini Clothes",
  "Cowls Neck Mini Cloth",
  "Cowls Neck Micro Mini Dresses",
  "Cowls Neck Micro Mini Dress",
  "Cowls Neck Micro Mini Clothing",
  "Cowls Neck Micro Mini Clothes",
  "Cowls Neck Micro Mini Cloth",
  "Cowls Neck Short Dresses",
  "Cowls Neck Short Dress",
  "Cowls Neck Short Clothing",
  "Cowls Neck Short Clothes",
  "Cowls Neck Short Cloth",
  "Cowls Neck es",
  "Cowls Neck ",
  "Cowls Neck",
  "Cowls Neck Short Dress Clothes",
  "Cowls Neck Short Dress Cloth",
  "Cowls Neck Short Dresses Dresses",
  "Cowls Neck Short Dresses Dress",
  "Cowls Neck Short Dresses Clothing",
  "Cowls Neck Short Dresses Clothes",
  "Cowls Neck Short Dresses Cloth",
  "Cowls Minis Dresses",
  "Cowls Minis Dress",
  "Cowls Minis Clothing",
  "Cowls Minis Clothes",
  "Cowls Minis Cloth",
  "Cowls Mini Dresses",
  "Cowls Mini Dress",
  "Cowls Mini Clothing",
  "Cowls Mini Clothes",
  "Cowls Mini Cloth",
  "Cowls Micro Mini Dresses",
  "Cowls Micro Mini Dress",
  "Cowls Micro Mini Clothing",
  "Cowls Micro Mini Clothes",
  "Cowls Micro Mini Cloth",
  "Cowls Short Dresses",
  "Cowls Short Dress",
  "Cowls Short Clothing",
  "Cowls Short Clothes",
  "Cowls Short Cloth",
  "Cowls es",
  "Cowls ",
  "Cowls",
  "Cowls Short Dress Clothes",
  "Cowls Short Dress Cloth",
  "Cowls Short Dresses Dresses",
  "Cowls Short Dresses Dress",
  "Cowls Short Dresses Clothing",
  "Cowls Short Dresses Clothes",
  "Cowls Short Dresses Cloth",
  "Cowl Neck Minis Dresses",
  "Cowl Neck Minis Dress",
  "Cowl Neck Minis Clothing",
  "Cowl Neck Minis Clothes",
  "Cowl Neck Minis Cloth",
  "Cowl Neck Mini Dresses",
  "Cowl Neck Mini Dress",
  "Cowl Neck Mini Clothing",
  "Cowl Neck Mini Clothes",
  "Cowl Neck Mini Cloth",
  "Cowl Neck Micro Mini Dresses",
  "Cowl Neck Micro Mini Dress",
  "Cowl Neck Micro Mini Clothing",
  "Cowl Neck Micro Mini Clothes",
  "Cowl Neck Micro Mini Cloth",
  "Cowl Neck Short Dresses",
  "Cowl Neck Short Dress",
  "Cowl Neck Short Clothing",
  "Cowl Neck Short Clothes",
  "Cowl Neck Short Cloth",
  "Cowl Neck es",
  "Cowl Neck ",
  "Cowl Neck",
  "Cowl Neck Short Dress Clothes",
  "Cowl Neck Short Dress Cloth",
  "Cowl Neck Short Dresses Dresses",
  "Cowl Neck Short Dresses Dress",
  "Cowl Neck Short Dresses Clothing",
  "Cowl Neck Short Dresses Clothes",
  "Cowl Neck Short Dresses Cloth",
  "Cowl Detailed Minis Dresses",
  "Cowl Detailed Minis Dress",
  "Cowl Detailed Minis Clothing",
  "Cowl Detailed Minis Clothes",
  "Cowl Detailed Minis Cloth",
  "Cowl Detailed Mini Dresses",
  "Cowl Detailed Mini Dress",
  "Cowl Detailed Mini Clothing",
  "Cowl Detailed Mini Clothes",
  "Cowl Detailed Mini Cloth",
  "Cowl Detailed Micro Mini Dresses",
  "Cowl Detailed Micro Mini Dress",
  "Cowl Detailed Micro Mini Clothing",
  "Cowl Detailed Micro Mini Clothes",
  "Cowl Detailed Micro Mini Cloth",
  "Cowl Detailed Short Dresses",
  "Cowl Detailed Short Dress",
  "Cowl Detailed Short Clothing",
  "Cowl Detailed Short Clothes",
  "Cowl Detailed Short Cloth",
  "Cowl Detailed es",
  "Cowl Detailed ",
  "Cowl Detailed",
  "Cowl Detailed Short Dress Clothes",
  "Cowl Detailed Short Dress Cloth",
  "Cowl Detailed Short Dresses Dresses",
];

// Convert array to JSON string
const jsonString = JSON.stringify(array);

// Calculate size in bytes
const byteSize = new TextEncoder().encode(jsonString).length;

// Convert bytes to kilobytes
const kilobyteSize = byteSize / 1024;

console.log(`Length: ${array.length}`);
console.log(`Size in bytes: ${byteSize} bytes`);
console.log(`Size in kilobytes: ${kilobyteSize.toFixed(2)} KB`);
